const MessageConstants = {
  ALL_EVENTS:"All Events",
  SELECTED_EVENTS:"Selected Events",
  CURRENT_USER:"",



  INTERNAL_ACCOUNT_NUMBER: "",
  EXTERNAL_ACCOUNT_NUMBER: "",
  ACCOUNT_NAME: "",
  COUNTRY_CODE: "",
  BILL_FRANCHISE_TAX_CODE: "",
  TAX_EXEMPTION_YES_NO:"",
  LOGIN_CRED: "Login with your Credentials",
  INVALID_CRED: "Invalid Credentials",
  LOGIN_SUCCESS: "Login Sucessful",
  LOGIN: "Login",
  LOGINAGAIN: "Please click here to re-login!",
  LOGOUT: "You are logged out!",
  THANKYOU: "Thank You for your time.",
  SEARCH: "Search account number",
  CUST360VIEW: "Customer 360 View",
  GSTNUM: "GST Number",
  TAX: "Tax Exemeption",
  PAYDUE: "Payment Due",
  LASTPAYDATE: "Last Payment Date",
  LASTPAYAMOUNT: "Last Payment Amount",
  LASTBILLDATE: "Last Bill Generation Date",
  BILLCYCLE: "Bill Cycle",
  LICEN: "Licensing Company",
  LEGAL: "Legal Entity",
  CURRENCY: "Currency",
  ACCTYPE: "Account Type",
  ADJUSTMENT: "Adjustment",
  INVOICE: "Invoice",
  PAYMENT: "Payment",
  POSTADJUSTMENT: "Post Adjustment",
  ADJUSTMENTDETAILS: "Adjustment Details",
  INVOICEDETAILS: "Invoice Details",
  DOWNLOADINVOICE: "Download Invoice",
  PAYMENTDETAILS: "Payment Details",
  SELECT: "Select Item",
  POSTNRC: "Post NRC",
  TAXEXEMPTION: "Tax Exemption",
  COUNTRYCODE: "Country Code",
  BILLFRANCHISETAXCODE: "Franchise Code",
  FINANCIAL: "Financial",

  CSIN: "CSIN",
  ACTIONCODE: "Action Code",
  DESCRIPTIONTEXT: "Description Text",
  ANNOTATAION: "Annotation",
  BILLREFRESETS: "Bill Ref Resets",
  TRACKINGID: "Tracking Id",
  TRACKINGIDSERV: "Tracking Id Serv",
  ORIGBILLREFRESETS: "Orig Bill Ref Resets",
  ORIGCSIN: "Orig Csin",
  TRANSACTDATE: "Transact Date",
  BILLREFNO: "Bill Ref No",
  ORIGBILLREFNO: "Orig Bill Ref no",
  ADJREASONCODE: "Adj Reason Code",
  SOURCENAME: "Source Name",
  TRANSTARGETTYPE: "Trans Target Type",
  TRACKINGIDCOUNTER: "Tracking Id Counter",
  PRIMARYUNITSTYPE: "Primary Units Type",
  REQUESTSTATUS: "Request Status",
  TOTALAMOUNT: "Total Amount",
  FEDERALTAX: "Federal Tax",
  TRANSSIGN: "Trans Sign",
  SUPERVISORNAME: "Supervisor Name",
  ADJTRANSCODE: "Adj Trans Code",
  EFFECTIVEDATE: "Effective Date",

  BMFTRANSTYPE: "Bmf Trans Type",
  POSTDATE: "Post Date",
  TRANSAMOUNT: "Trans Amount",
  PAYMETHOD: "Pay Method",
  TRANSSOURCE: "Trans Source",
  TRANSSUBMITTER: "Trans Submitter",
  EXTERNALCURRENCY: "External Currency",
  MICRBANKID: "Micr Bank Id",

  ACCOUNTNO: "Account No",
  BALANCEDUE: "Balance Due",
  CLOSEDDATE: "Closed Date",
  FROMDATE: "From Date",
  LATEEXEMPTCHARGES: "Late Exempt Charges",
  NETNEWCHARGES: "Net New Charges",
  NEWCHARGECREDITS: "New Charge Credits",
  NEWCHARGES: "New Charges",
  ORIGPPDDDATE: "Orig Ppdd Date",
  PAYMENTDUEDATE: "Payment Due Date",
  PREPDATE: "Prep Date",
  STATEMENTDATE: "Statement Date",
  TODATE: "To Date",
  TOTALADJ: "Total Adj",
  TOTALDUE: "Total Due",
  TOTALPAID: "Total Paid",
  CARRIEDFORWARD: "Carried Forward",
  NOOFMONTHS: "No Of Months",


  AddAgent:"Add Agent",
  AgentRole:"Role",
  AgentActiveFrom:"Active From",
  AgentActiveTill:"Active Till",
  AgentOlmId:"OLM ID",
  AgentFirstName:"First Name",
  AgentLastName:"Last Name",
  AgentContactNo:"Contact Details",
  AgentEmailId:"Email",

  CopyRole:"Create New Role",
  CopyRoleFrom:"Copy From",
  NewRoleDetail:"New Role Description",
  NewRoleId:"New Role Id",
  NewRoleDescription:"Role Description",
  ViewRole:"View Role",
  ViewRoleId:"Select Role to View",

  GenerateReport:"Generate Report",
  SelectReport:"Report",
  SubmitButton:"Submit",
  CleanButton:"Clean",
  CancelButton:"Cancel",
  CreateButton:"Create",
};

export default MessageConstants;
